export const Code = {
  RC01_AOBPR_AL_SEX: 'RC01_AOBPR_AL_SEX', // 性别
  RC01_AOBPR_AL_YES_NO: 'RC01_AOBPR_AL_YES_NO', // 是否
  RC01_AOBPR_AL_SWITCH_ON_OFF: 'RC01_AOBPR_AL_SWITCH_ON_OFF', // 开关
  ZY02_AOBPR_COMPU_LANG: 'ZY02_AOBPR_COMPU_LANG' // 计算机语言
};
export const RC01_AOBPR_AL_SWITCH_ON_OFF = {
  SWITCH_OFF: 'SWITCH_OFF',
  SWITCH_ON: 'SWITCH_ON'
};
export const RC01_AOBPR = 'RC01_AOBPR';
export const ZY02_AOBPR = 'ZY02_AOBPR';
